Fri May  1 15:53:05 CEST 2020

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ jobs:
 
       - name: Setup test as clippy
         if: ${{ matrix.command == 'cargo test' }}
-        run: echo '#!/bin/sh -e\n\nshift\nexec cargo test --no-fail-fast "$@"' > "`which cargo-clippy`"
+        run: echo '#!/bin/sh -e\n\nshift\ncargo test --no-fail-fast "$@" || exit 101' > "`which cargo-clippy`"
 
       - name: Run clippy
         if: ${{ matrix.command == 'cargo test' }}
